FIneract-1348-balloon-payment-fixed-principal-percentage
apache/fineract pull request #1702
Opened 2021-04-17 11:23 UTC by fynmanoj

## Description
https://issues.apache.org/jira/browse/FINERACT-1348
Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2021-09-10 14:31 UTC, awasum commented
Hi @fynmanoj  Sorry for the delay. There are now merge conflicts on the PR. 

@francisguchie , @bharathc27 you can test this function together with the UI changes found here: https://github.com/openMF/community-app/pull/3381

2021-09-10 14:36 UTC, fynmanoj commented
@awasum , I have rebased the PR

2021-09-21 14:34 UTC, ptuomola requested changes

2021-09-21 14:34 UTC, ptuomola commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/loanaccount/domain/Loan.java
> +        }
Shouldn't this be this.fixedPrincipalPercentagePerInstallment, not this.fixedEmiAmount?

2021-10-11 10:48 UTC, avikganguly01 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/loanaccount/domain/Loan.java
> +        }
@fynmanoj : Can you confirm this and rebase it again? Rest of it looks good.

2021-10-11 11:53 UTC, fynmanoj commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/loanaccount/domain/Loan.java
> +        }
done!

2021-10-11 12:01 UTC, avikganguly01 approved these changes

2021-10-11 12:02 UTC, merged

2021-10-23 09:50 UTC, awasum commented
Please lets make it a habit not to merge PRs when Travis Tests have not passed. Can you close the corresponding issue on JIRA please...