FINERACT-982 - Completely ditch use of Drizzle JDBC Driver after all
apache/fineract pull request #1883
Opened 2021-09-24 04:36 UTC by IOhacker

## Description

Changes were done for replacing the Drizzle JDBC Driver as per issue reported at FINERACT-982 - Completely ditch use of Drizzle JDBC Driver after all. Now using MariaDB with charset utf8mb4 and collation utf8_unicode_ci

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ X] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ X] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ X] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2021-10-02 16:12 UTC, avikganguly01 commented
@IOhacker : Can you please test if MariaDB driver will work with AWS RDS (and if possible with Azure's managed MySQL database)?

2021-10-02 16:51 UTC, IOhacker commented
I can, or what about testing this JDBC Driver, which is for AWS
https://github.com/awslabs/aws-mysql-jdbc

El sáb, 2 oct 2021 a las 11:13, Avik Ganguly ***@***.***>)
escribió:

> @IOhacker <https://github.com/IOhacker> : Can you please test if MariaDB
> driver will work with AWS RDS (and if possible with Azure's managed MySQL
> database)?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/apache/fineract/pull/1883#issuecomment-932777208>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALD2ZATLHW7NEKJEJFDDU6DUE4VRLANCNFSM5EVDHLWA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-09 02:08 UTC, ptuomola requested changes

2021-10-09 02:08 UTC, ptuomola commented on LICENSE_RELEASE
If my understanding is correct, I don't think we are allowed to bundle anything with a LGPL license. We can make the JDBC driver a dependency so that is is downloaded at build / run time - that way the users can choose to use another, non-LGPL'd, JDBC driver. But we should not bundle anything in our release.

2021-10-09 02:08 UTC, ptuomola commented on build.gradle
>              dependency 'com.github.librepdf:openpdf:1.3.26'
Given that we can't bundle a LGPL driver, we need to find some way to a) use it as a dependency in the classpath but b) not bundle it in the release JAR. I'd suggest experimenting with the different gradle classpaths to do this (e.g. is it adding this to runtimeClasspath rather than implementationClasspath?)

2021-10-11 10:45 UTC, avikganguly01 commented on build.gradle
>              dependency 'com.github.librepdf:openpdf:1.3.26'
@IOhacker @ptuomola : In terms of bundling it as a dependency as an optional build time flag instead of putting it in the release JAR, there is a complication : -
There are places in the code where return type casting is based on Drizzle (search Drizzle in codebase). There is no consistency between JDBC drivers when it comes to some return types so this needs some work in those source files as well.

2021-10-17 03:22 UTC, BLasan commented
@IOhacker Please resolve the conflicts

2021-11-03 00:06 UTC, ptuomola commented on build.gradle
>              dependency 'com.github.librepdf:openpdf:1.3.26'
@IOhacker @avikganguly01 I wonder if we need the equivalent code if we are using MariaDB? A lot of the code is to handle Drizzle's peculiarities re return types. Now OpenJPA supports MariaDB "out of the box" so there may not be any need to customise the JDBC behaviour. 

Also interesting... if we've dropped all dependencies to Drizzle but the code is doing casting based on the Drizzle classes, how does this still compile? I'd expect to get a compilation error.

2021-11-03 00:11 UTC, ptuomola commented
@IOhacker I think we should also update README.md to give people instructions to use MariaDB rather than MySQL, and .travis.yml to use MariaDB.

2021-11-27 07:14 UTC, ptuomola commented
Hi @IOhacker - will you have time to finish this one off? I can give it a go if you're busy - would be great to get this implemented...

2021-12-23 14:03 UTC, ptuomola commented
Changes incorporated in #1990

2021-12-23 14:03 UTC, closed without merging