Semi-Monthly Feature (FINERACT-1322)
apache/fineract pull request #1884
Opened 2021-09-27 19:45 UTC by Cadreia

## Description

* Implements the semi-monthly loan scheduler feature.
* Details of this issue can be found on this [Apache Fineract JIRA ticket](https://issues.apache.org/jira/browse/FINERACT-1322).
* An [article](http://research.muellners.org/implementing-a-bi-monthly-loan-product/) has been written on this.
* Corresponding UI change is [here](https://github.com/openMF/community-app/pull/3422).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2021-10-09 00:52 UTC, ptuomola requested changes
Also have we tested what happens if one of the semi dates falls on a date which does not exist in every month - i.e. 31st? Does the logic work sensibly in that case as well?

2021-10-09 00:52 UTC, ptuomola commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/loanaccount/service/LoanApplicationWritePlatformServiceJpaRepositoryImpl.java
> +            // newLoanApplication.getTermPeriodFrequencyType(), productRelatedDetail.getNumberOfRepayments(),
Why is this validation commented out?

2021-10-09 00:52 UTC, ptuomola commented on integration-tests/src/test/java/org/apache/fineract/integrationtests/LoanDisbursementDetailsIntegrationTest.java
Why have these test results changed? I would not expect the existing integration tests to have to change when adding new products...

2021-10-12 21:39 UTC, BLasan commented
@Cadreia Please resolve merge conflicts and requested changes by @ptuomola

2021-10-12 21:54 UTC, BLasan requested changes

2021-10-12 21:54 UTC, BLasan commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/loanaccount/data/LoanAccountData.java
> -        final EnumOptionData termPeriodFrequencyType = product.getRepaymentFrequencyType();
Any reassignments?

2021-10-12 21:54 UTC, BLasan commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/loanproduct/data/LoanProductData.java
> +            Collection<RateData> rateOptions, Collection<RateData> rates, final boolean isRatesEnabled, final LocalDate firstDateForSemi,
Why `rateOptions` and `rates` are not final? Any reassignment?

2021-10-12 21:54 UTC, BLasan commented on integration-tests/src/test/java/org/apache/fineract/integrationtests/LoanDisbursementDetailsIntegrationTest.java
> +        assertEquals(Float.parseFloat(period.get("principalLoanBalanceOutstanding").toString()),
Why converted to a Float comparison?

2021-10-13 19:55 UTC, awasum commented
@Cadreia , Please resolve merge conflicts here and address review comments above.

2021-11-13 16:30 UTC, BLasan commented
@Cadreia Could you please address the review comments?

2022-01-13 02:47 UTC, awasum commented
@Cadreia Please fix review comments and merge conflicts so this can be reviewed and merged. Important feature.

2022-03-15 00:12 UTC, closed without merging