FINERACT-1604: Fix Loan Account Details page not working
apache/fineract pull request #2301
Opened 2022-04-27 21:57 UTC by josehernandezfintecheandomx

## Description

Update the method to support no data result from the query loan collection data

More details in [Apache Fineract JIRA ticket FINERACT-1604](https://issues.apache.org/jira/browse/FINERACT-1604).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2022-04-27 22:02 UTC, vidakovic approved these changes
LGTM

2022-04-28 13:55 UTC, galovics requested changes

2022-04-28 13:55 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/loanaccount/service/LoanReadPlatformServiceImpl.java
> +        List<CollectionData> collectionDatas = this.jdbcTemplate.query(sql, mapper, new Object[] { loanId });
Please don't remove the // NOSONAR comment.

2022-04-28 21:28 UTC, John-Woodlock commented
talked with Alberto because I'm pretty sure it is the query that is the problem (inner join rather than left join for m_loan_arrears_aging).  Either the query has changed or the Java logic has changed slightly.  No need to merge this PR.  Agreed with Alberto to issue another PR with 'inner' to 'left' shortly.

2022-04-29 13:21 UTC, closed without merging