[Focus: Customer/Developer] Add placeholder document for business date
apache/fineract pull request #2490
Opened 2022-08-08 08:14 UTC by tapaswenipathak

Ref:
- Write new documentation on transaction idempotency and business and effective date configuration
- Business & Effective Date Separation - https://github.com/apache/fineract/pull/2358/files
- https://mifosforge.jira.com/wiki/spaces/P/pages/3079733251/Introducing+Business+Date+into+Fineract+community+version
- https://github.com/openMF/mifos-documentation/issues/14

cc @edcable. 

## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2022-08-22 13:09 UTC, galovics commented
@tapaswenipathak are there any plans to make this PR ready? Do you need help with it?

2022-08-23 07:50 UTC, tapaswenipathak commented
plans: yes. soon, this week most probably, a couple of more or a bunch.

cc @edcable.

On Monday, August 22, 2022, Arnold Gálovics ***@***.***>
wrote:

> @tapaswenipathak <https://github.com/tapaswenipathak> are there any plans
> to make this PR ready? Do you need help with it?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/apache/fineract/pull/2490#issuecomment-1222338156>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA7TVISU2HVWDJ2NUB2LGDDV2N3ZHANCNFSM554GBPRQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-23 12:25 UTC, vidakovic commented
@tapaswenipathak would be great if you could format the PR title according to this pattern: "FINERACT-XXXX: Title of Jira ticket". If there's no Jira ticket yet and you are unable to create one yourself then please contact me, I'll help out. Thanks.

2022-08-23 13:56 UTC, tapaswenipathak commented
sure, but i dont't think any jira ticket(s) exist, can you sync w/ Ed on
slack? please loop me in, if there is anything i can help w/.

On Tuesday, August 23, 2022, Aleksandar Vidakovic ***@***.***>
wrote:

> @tapaswenipathak <https://github.com/tapaswenipathak> would be great if
> you could format the PR title according to this pattern: "FINERACT-XXXX:
> Title of Jira ticket". If there's no Jira ticket yet and you are unable to
> create one yourself then please contact me, I'll help out. Thanks.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/apache/fineract/pull/2490#issuecomment-1223997174>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA7TVIWITWO6ZXVFQO4WBZDV2S7MPANCNFSM554GBPRQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-23 14:03 UTC, tapaswenipathak commented
looped in both of you in the email. not sure if there should be one,
multiple or no jira ticket.

On Tuesday, August 23, 2022, Tapasweni Pathak ***@***.***>
wrote:

> sure, but i dont't think any jira ticket(s) exist, can you sync w/ Ed on
> slack? please loop me in, if there is anything i can help w/.
>
> On Tuesday, August 23, 2022, Aleksandar Vidakovic ***@***.***>
> wrote:
>
> > @tapaswenipathak <https://github.com/tapaswenipathak> would be great if
> > you could format the PR title according to this pattern: "FINERACT-XXXX:
> > Title of Jira ticket". If there's no Jira ticket yet and you are unable
> to
> > create one yourself then please contact me, I'll help out. Thanks.
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <https://github.com/apache/fineract/pull/2490#issuecomment-1223997174>,
> > or unsubscribe
> > <https://github.com/notifications/unsubscribe-auth/
> AA7TVIWITWO6ZXVFQO4WBZDV2S7MPANCNFSM554GBPRQ>
> > .
> > You are receiving this because you were mentioned.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/apache/fineract/pull/2490#issuecomment-1224114646>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA7TVIV4DOAABFFUYYTQV2TV2TKCTANCNFSM554GBPRQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-10-10 16:22 UTC, galovics requested changes

2022-10-10 16:22 UTC, galovics commented on fineract-doc/src/docs/en/chapters/documentation/business-date.adoc
> += Introducing Business Date into Fineract
Already present. https://fineract.apache.org/docs/current/#_introducing_business_date_into_fineract_community_version

2022-10-11 05:40 UTC, tapaswenipathak commented on fineract-doc/src/docs/en/chapters/documentation/business-date.adoc
> += Introducing Business Date into Fineract
cc @edcable.

2022-12-17 00:13 UTC, closed without merging