FINERACT-1742: Introduce Lombok to dataqueries module
apache/fineract pull request #2591
Opened 2022-09-11 07:58 UTC by hmg65

## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [x] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2022-09-13 13:47 UTC, galovics requested changes

2022-09-13 13:47 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/dataqueries/data/ResultsetColumnHeaderData.java
> -    public boolean isNamed(final String columnName) {
Why delete this one?

2022-09-13 13:47 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/dataqueries/data/ResultsetColumnHeaderData.java
> -    public boolean isMandatory() {
Why delete this one?

2022-09-13 13:47 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/dataqueries/data/ResultsetColumnHeaderData.java
> -    public boolean isOptional() {
Why delete this one?

2022-09-13 13:47 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/dataqueries/data/ResultsetColumnHeaderData.java
> -    public boolean hasColumnValues() {
Why delete this one?

2022-09-13 13:47 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/dataqueries/data/ResultsetColumnHeaderData.java
> -    public boolean isColumnValueNotAllowed(final String match) {
Why delete this one?

2022-09-13 13:47 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/dataqueries/data/ResultsetColumnHeaderData.java
> -    public boolean isColumnCodeNotAllowed(final Integer match) {
Why delete this one?

2022-09-13 13:47 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/dataqueries/service/ReadWriteNonCoreDataServiceImpl.java
> -        if (grs.hasMoreThanOneEntry()) {
Why deleted the original method?

2022-10-11 00:19 UTC, hmg65 commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/dataqueries/service/ReadWriteNonCoreDataServiceImpl.java
> -        if (grs.hasMoreThanOneEntry()) {
i have directly implemented it

2022-10-11 00:19 UTC, hmg65 commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/dataqueries/data/ResultsetColumnHeaderData.java
> -    public boolean isColumnCodeNotAllowed(final Integer match) {
fixed

2022-10-11 00:19 UTC, hmg65 commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/dataqueries/data/ResultsetColumnHeaderData.java
> -    public boolean isColumnValueNotAllowed(final String match) {
fixed

2022-10-11 00:20 UTC, hmg65 commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/dataqueries/data/ResultsetColumnHeaderData.java
> -    public boolean hasColumnValues() {
fixed

2022-10-11 00:20 UTC, hmg65 commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/dataqueries/data/ResultsetColumnHeaderData.java
> -    public boolean isOptional() {
fixed

2022-10-11 00:20 UTC, hmg65 commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/dataqueries/data/ResultsetColumnHeaderData.java
> -    public boolean isMandatory() {
fixed

2022-10-11 00:20 UTC, hmg65 commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/dataqueries/data/ResultsetColumnHeaderData.java
> -    public boolean isNamed(final String columnName) {
directly implemented it at the usage

2022-12-13 00:16 UTC, closed without merging