[FINERACT-1678] Inline COB API
apache/fineract pull request #2675
Opened 2022-10-15 03:17 UTC by taskain7

## Description

This PR introduces the Inline Loan COB job.
A new API has been introduced to execute Inline COBs.

2022-10-15 09:06 UTC, galovics requested changes
Overall I'm still confused by the naming in the PR. The inline functionality is not tied to COBs but any partitioned job in the future. Let's get rid of this naming and be more generic.

Plus, I'd love to see at least a single integration test for the inline COB's positive scenario.

2022-10-15 09:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/api/InlineCOBResource.java
> +    @Path("{COBJobName}/inline")
Doesn't have to be `COBJobName`. Simply `jobName` is enough.

2022-10-15 09:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/api/InlineCOBResource.java
> +public class InlineCOBResource {
Doesn't need to be COB specific. Any jobs in the future which are partitioned could have an inline alternative.

2022-10-15 09:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/api/InlineCOBResource.java
> +    @Operation(summary = "Starts an inline COB", description = "Starts an inline COB")
Not COB only.

2022-10-15 09:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/loan/InlineCOBBuildExecutionContextTasklet.java
> +                LoanCOBConstant.LOAN_COB_JOB_NAME);
Since this tasklet is a generic one for inline execution, we can't hardcode the LOAN_COB_JOB_NAME, can we?

2022-10-15 09:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/loan/InlineCOBBuildExecutionContextTasklet.java
> +        contribution.getStepExecution().getExecutionContext().put(LoanCOBConstant.LOAN_IDS, inlineCOBExecutorService.getLoanIds());
Same as above, this is LOAN_COB specific.

2022-10-15 09:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/loan/LoanInlineCOBConfig.java
> +        return stepBuilderFactory.get(JobName.ACCOUNTING_RUNNING_BALANCE_UPDATE.name()).tasklet(inlineCOBBuildExecutionContextTasklet())
Copy paste error with the job name.

2022-10-15 09:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/loan/LoanInlineCOBConfig.java
> +                .faultTolerant().skip(Exception.class).skipLimit(propertyService.getChunkSize(JobName.LOAN_COB.name()) + 1)
I think we shouldn't allow skipping here. If the inline Loan COB fails, it should fail and respond synchronously.

2022-10-15 09:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/loan/LoanInlineCOBConfig.java
> +    public InlineCOBLoanItemReader inlineCobWorkerItemReader() {
Why can we reuse these beans from the regular Loan COB? I think with minimal refactorings to them it could be easily reused..

2022-10-15 09:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/loan/LoanItemWriter.java
> +        accountLockRepository.deleteByLoanIdInAndLockOwner(loanIds, LockOwner.LOAN_INLINE_COB_PROCESSING);
Not sure why this is needed, can you please explain?

2022-10-15 09:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/listener/LoanItemListener.java
> +                    if (loanAccountLock.isEmpty()) {
Not sure why this is needed, explain please.

2022-10-15 09:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/service/InlineCOBExecuteHandler.java
> +        List<String> split = Splitter.on("/").splitToList(command.getUrl());
Why do we need this splitting? The REST layer can easily get you access to the path/query parameters with annotations, lets not reinvent the wheel.

2022-10-15 09:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/service/InlineCOBExecutionDataParser.java
> +            Long loanId = jsonHelper.extractLongNamed("loanId", loanIdElement);
Doesn't this mean that in the array we have every single element as object and inside that a loanId?
Something like this:
```
{
  "loanIds": [
    { "loanId": 1},
    { "loanId": 2}
  ]
}
```

If this is the case, why can't we just go with a plain, primitive array?
```
{
  "loanIds": [
    1,
    2
  ]
}
```

2022-10-15 09:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/service/InlineCOBType.java
> +        Optional<InlineCOBType> optionalCategory = Arrays.stream(InlineCOBType.values())
variable naming, not sure about "category", maybe just a copy paste error.

2022-10-15 09:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/service/InlineCOBType.java
> +    InlineCOBType(String jobName, String inlineCOBJobName, Class<? extends InlineCOBExecutorService> executorServiceClass) {
Can be replaced with a RequiredArgsConstructor

2022-10-15 09:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/service/InlineCOBType.java
> +    final String jobName;
Mark them as private please.

2022-10-15 09:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/service/InlineLoanCOBExecutorServiceImpl.java
> +    private List<Long> loanIds;
Okay, this is definitely not the way to go. You can a Spring bean that's a singleton and you just made it stateful. What happens if there are concurrent executions? It'll mess up the state.

2022-10-15 09:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/service/InlineLoanCOBExecutorServiceImpl.java
> +                .addJobParameters(new JobParameters()).toJobParameters();
Why don't we add the loanIds as a job parameter as well?

2022-10-15 09:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/service/InlineLoanCOBExecutorServiceImpl.java
> +            log.error("{}", msg);
What's the point of this? With the String concatenation above you're defeating the purpose of placeholders in the logger. Should inline the log message and pass the jobName as a parameter.

2022-10-15 09:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/service/InlineLoanCOBExecutorServiceImpl.java
> +            loanAccountLockRepository.save(loanAccountLock);
So the public method is not allowing transactions which means that this save call is opening and closing transactions for every single loan account lock, that's definitely not the way to go. All loan accounts shall be locked in a single tx

2022-10-15 19:59 UTC, jdailey reviewed
I'm certain we can improve test coverage

2022-10-17 11:05 UTC, galovics requested changes

2022-10-17 11:05 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/loan/InlineCOBLoanItemProcessor.java
> +        executionContext = stepExecution.getJobExecution().getExecutionContext();
A setter would be nicer.

2022-10-17 11:05 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/loan/InlineLoanCOBBuildExecutionContextTasklet.java
> +        chunkContext.getStepContext().getJobParameters().forEach((k, v) -> {
I don't get this logic. Why can't we put all the LoanIDs under a single key?

2022-10-17 11:05 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/loan/LoanItemProcessor.java
> +    @BeforeStep
Why do we need the annotation if the interface is implemented?

2022-10-17 11:05 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/loan/LoanItemProcessor.java
> +        executionContext = stepExecution.getExecutionContext();
A setter would be nicer.

2022-10-17 11:05 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/loan/InlineCOBLoanItemReader.java
> +    @BeforeStep
Why the annotation if the interface is implemented?

2022-10-17 11:05 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/loan/InlineCOBLoanItemReader.java
> +        remainingData = new ArrayList<>(loanIds);
A setter would be nicer.

2022-10-17 11:05 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/loan/InlineCOBLoanItemProcessor.java
> +    @BeforeStep
Why the annotation if the interface is implemented?

2022-10-17 11:05 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/loan/LoanItemReader.java
>      @BeforeStep
Annotation is not needed since the interface is implemented.

2022-10-17 11:05 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/loan/LoanItemReader.java
>          remainingData = new ArrayList<>(loanIds);
Setter would be nicer.

2022-10-17 11:05 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/service/InlineCOBExecuteHandler.java
> +        List<String> split = Splitter.on("/").splitToList(command.getUrl());
Still don't agree with this, please fix it.

2022-10-17 11:05 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/service/InlineCOBExecutionDataParser.java
> +public class InlineCOBExecutionDataParser {
Isn't this inline Loan COB specific? (not inline COB)

2022-10-17 11:05 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/service/InlineLoanCOBExecutorServiceImpl.java
> +    private List<LoanAccountLock> getLoanAccountLocks(List<Long> loanIds) {
This whole thing should be done in a singular transaction along with the locking to avoid the check-then-act race condition.

2022-10-17 11:05 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/service/InlineLoanCOBExecutorServiceImpl.java
> +        for (Long loanId : loanIds) {
Not sure why we cant put all the loanIds into a single param (?)

2022-10-18 16:06 UTC, galovics approved these changes

2022-10-18 17:14 UTC, merged