[FINERACT-1678] Introducing synchronous COB execution for loan account changing APIs
apache/fineract pull request #2731
Opened 2022-11-07 10:19 UTC by taskain7

## Description

When a loan is soft locked by COB partitioning during write operation, then the Inline COB runs on the loan instead of regular COB and after that the write operation goes through.

2022-11-07 11:25 UTC, galovics requested changes

2022-11-07 11:25 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/service/LoanAccountLockServiceImpl.java
> +        Optional<LoanAccountLock> loanAccountLockOptional = loanAccountLockRepository.findById(loanId);
I think it's not needed to fetch the actual entity. Let's write a custom repository method for this.
Something like `existsByIdAndLockOwner`

2022-11-07 11:25 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/core/config/SecurityConfig.java
> +                .addFilterAfter(twoFactorAuthenticationFilter, LoanCOBApiFilter.class); //
So where do the BasicAuthenticationFilter go?

2022-11-07 11:25 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/jobs/filter/LoanCOBApiFilter.java
> +        inlineLoanCOBExecutorService.lockLoanAccounts(loanIds);
Hmm, I'm thinking about the responsibilities. I think it'd be better if the service itself locks the loan accounts, don't you think?
Like that's a unit in itself. You instruct the service "let's run the inline COB for these loan accounts" and you should expect that everything is taken care of.

2022-11-07 11:25 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/service/InlineLoanCOBExecutorServiceImpl.java
> +    public void execute(List<Long> loanIds, String jobName) {
Can't we add this method to the interface with a generic T type which refers to the entity ID type?

2022-11-07 16:56 UTC, galovics requested changes

2022-11-07 16:56 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/cob/service/InlineLoanCOBExecutorServiceImpl.java
> +public class InlineLoanCOBExecutorServiceImpl implements InlineExecutorService<List<Long>>, InitializingBean {
What if we  simply don't specify the List part of the generic parameter? Just the Long. That way all the interface implementors will have the same List input type for the method.

2022-11-07 16:56 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/jobs/service/InlineExecutorService.java
> +    void execute(T id, String jobName);
So rather this should look like:
```
void execute(List<T> elements, String jobName);
```

Plus, it'd be good to provide a way to do the same thing for a single item, so like we could add this:
```
default void execute(T element, String jobName) {
    execute(singletonList(element), jobName)
}
```
Thoughts?

2022-11-08 09:48 UTC, taskain7 commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/jobs/service/InlineExecutorService.java
> +    void execute(T id, String jobName);
makes sense, I've chenged it.

2022-11-08 13:46 UTC, galovics approved these changes

2022-11-08 13:46 UTC, merged