Notification Module
apache/fineract pull request #283
Opened 2017-01-29 21:35 UTC by ad-os

This module will allow developers to integrate notifications with their functionality. Here are some wikis on which you can read more about this module.

1) [Notification Module Design](https://mifosforge.jira.com/wiki/pages/viewpage.action?pageId=133070890)
2) [Notification API Developer User Guide](https://mifosforge.jira.com/wiki/display/MDZ/Notification+API+Developer+User+Guide)
3) [Configure Notifications-End User guide](https://mifosforge.jira.com/wiki/display/docs/Configure+Notifications)

2017-01-31 07:18 UTC, nazeer1100126 approved these changes

2017-01-31 07:18 UTC, nazeer1100126 commented on fineract-provider/src/main/java/org/apache/fineract/notification/domain/Notification.java
> +    private Long actorId;
actor is text in notification_generator definition. But entity is defined with Long?

2017-01-31 07:18 UTC, nazeer1100126 commented on fineract-provider/src/main/java/org/apache/fineract/notification/service/NotificationGeneratorReadPlatformServiceImpl.java
> +public class NotificationGeneratorReadPlatformServiceImpl implements NotificationGeneratorReadPlatformService {
If you are reading Entity from NotificationRepository, do we need to have separate readplatform service? Why can't caller directly call method on NotificationRepository? Readplatforms are designed to use JDBCTemplate not Repositories.

2017-01-31 07:18 UTC, nazeer1100126 commented on fineract-provider/src/main/java/org/apache/fineract/notification/service/NotificationMapperReadPlatformServiceImpl.java
> +public class NotificationMapperReadPlatformServiceImpl implements NotificationMapperReadPlatformService {
Do we need this class? Why can't caller directly call methods on NotificationMapperRepository?
Read platform services are designed to use JDBCTemplate

2017-01-31 07:18 UTC, nazeer1100126 commented on fineract-provider/src/main/java/org/apache/fineract/notification/service/NotificationGeneratorReadPlatformServiceImpl.java
> +public class NotificationGeneratorReadPlatformServiceImpl implements NotificationGeneratorReadPlatformService {
Or are you trying as repository wrapper? In such case why the class name is read platform service?

2017-01-31 07:18 UTC, nazeer1100126 commented on fineract-provider/src/main/java/org/apache/fineract/notification/service/NotificationMapperReadPlatformServiceImpl.java
> +public class NotificationMapperReadPlatformServiceImpl implements NotificationMapperReadPlatformService {
Or are you trying as repository wrapper? In such case why the class name is read platform service?

2017-01-31 07:18 UTC, nazeer1100126 commented on fineract-provider/src/main/java/org/apache/fineract/notification/eventandlistener/NotificationEvent.java
> +public class NotificationEvent {
Is it a event or service?

2017-02-27 11:33 UTC, ad-os commented on fineract-provider/src/main/java/org/apache/fineract/notification/domain/Notification.java
> +    private Long actorId;
Sorry about that, when the last time I changed the actorId to Long, I forgot to change it in the notification_generator definition.

2017-02-27 14:11 UTC, ad-os commented on fineract-provider/src/main/java/org/apache/fineract/notification/service/NotificationGeneratorReadPlatformServiceImpl.java
> +public class NotificationGeneratorReadPlatformServiceImpl implements NotificationGeneratorReadPlatformService {
I am trying it as repository wrapper. What name should this class be named? Would it be NotificationGeneratorReadRepositoryWrapper?

2017-02-27 14:31 UTC, ad-os commented on fineract-provider/src/main/java/org/apache/fineract/notification/service/NotificationMapperReadPlatformServiceImpl.java
> +public class NotificationMapperReadPlatformServiceImpl implements NotificationMapperReadPlatformService {
I am trying it as repository wrapper. What name should this class be named? Would it be NotificationMapperReadRepositoryWrapper?

2017-02-27 14:35 UTC, ad-os commented on fineract-provider/src/main/java/org/apache/fineract/notification/eventandlistener/NotificationEvent.java
> +public class NotificationEvent {
It is a service which broadcast the notification event to an external queue.

2017-07-31 09:07 UTC, nazeer1100126 requested changes

2017-07-31 09:07 UTC, nazeer1100126 commented on fineract-provider/src/main/java/org/apache/fineract/notification/service/NotificationReadPlatformServiceImpl.java
> +    private HashMap<Long, CacheNotificationResponseHeader> notificationResponseHeaderCache = new HashMap<>();
Does this cache works in multi tenancy environment? What happens if two tenants have same user id?

2017-07-31 09:07 UTC, nazeer1100126 commented on fineract-provider/src/main/java/org/apache/fineract/notification/eventandlistener/NotificationEvent.java
> +public class NotificationEvent {
Rename this file to NotificationEventService

2017-07-31 09:07 UTC, nazeer1100126 commented on fineract-provider/src/main/java/org/apache/fineract/notification/service/NotificationGeneratorReadPlatformServiceImpl.java
> +public class NotificationGeneratorReadPlatformServiceImpl implements NotificationGeneratorReadPlatformService {
We follow an approach all read platforms should have jdbc template usage. In your it is not read platform it is just a wrapper. So it should be renamed to NotificationGeneratorReadRepositoryWrapper

2017-07-31 09:07 UTC, nazeer1100126 commented on fineract-provider/src/main/java/org/apache/fineract/notification/service/NotificationMapperReadPlatformServiceImpl.java
> +public class NotificationMapperReadPlatformServiceImpl implements NotificationMapperReadPlatformService {
Rename to NotificationMapperReadRepositoryWrapper

2017-07-31 18:32 UTC, ad-os commented on fineract-provider/src/main/java/org/apache/fineract/notification/service/NotificationReadPlatformServiceImpl.java
> +    private HashMap<Long, CacheNotificationResponseHeader> notificationResponseHeaderCache = new HashMap<>();
I think I missed this case. Do I need to implement this now or can we add this later in another PR?

2017-08-01 05:53 UTC, nazeer1100126 commented on fineract-provider/src/main/java/org/apache/fineract/notification/service/NotificationReadPlatformServiceImpl.java
> +    private HashMap<Long, CacheNotificationResponseHeader> notificationResponseHeaderCache = new HashMap<>();
Without this, I don't think this PR is useful.

2017-08-01 06:43 UTC, ad-os commented on fineract-provider/src/main/java/org/apache/fineract/notification/service/NotificationReadPlatformServiceImpl.java
> +    private HashMap<Long, CacheNotificationResponseHeader> notificationResponseHeaderCache = new HashMap<>();
It can be done. Just a little bit of work, need to associate tenant with user id's. Will try to complete as soon as possible 😄

2017-08-08 08:36 UTC, nazeer1100126 commented
@ad-os Changes looks ok. Can you resent PR with single commit please.

2017-08-09 08:15 UTC, nazeer1100126 commented
@ad-os as discussed over slack, You have added a library which is having dependency on BSD licensed third party library. Can you check the current binary licensing please.

2017-08-16 12:04 UTC, nazeer1100126 commented
@ad-os  Please refer LICENSE_RELEASE file. You need to add an entry about this BSD library.

2017-08-21 10:49 UTC, merged