FINERACT-1893: Run reports fix
apache/fineract pull request #2990
Opened 2023-02-19 22:10 UTC by vidakovic

Run reports fix

2023-02-20 09:12 UTC, galovics approved these changes

2023-02-22 08:47 UTC, adamsaghy requested changes, later dismissed
Please check the failing test.

2023-09-04 07:36 UTC, vidakovic commented
This PR is important and is needed for 1.9.0 release.

2023-11-07 06:55 UTC, vidakovic commented
This is still needed for the next release.

2024-01-06 17:58 UTC, merged