Publish Fineract Provider binary
apache/fineract pull request #3049
Opened 2023-03-15 06:41 UTC by IOhacker

Publish Fineract Provider binary

## Description

Publish Fineract Provider binary required for having gradle/maven repositories needed by the development of Fineract plugins 

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2023-03-15 06:52 UTC, vidakovic approved these changes
LGTM

2023-03-15 07:55 UTC, vidakovic commented
@IOhacker Restarted failed builds... FYI.

2023-03-15 16:18 UTC, galovics commented
@IOhacker this breaks the publish task for me locally and for openMF/fineract too. @vidakovic can you check it yourself? Thanks.

2023-03-15 20:25 UTC, francisguchie commented
@vidakovic could this be the reason why the fineract-pentaho plugin is failing to publish too? see this [issue](https://github.com/openMF/fineract-pentaho/issues/85)

2023-03-16 10:08 UTC, vidakovic commented
@galovics how can I test this? Do I need credentials to publish to the Maven repo?

2023-03-18 16:56 UTC, galovics commented
> @galovics how can I test this? Do I need credentials to publish to the Maven repo?

@vidakovic don't bother with creds, just do a ./gradlew publish locally and it'll fail.

The error is:
```
> Failed to publish publication 'mavenJava' to repository 'apache'
   > Invalid publication 'mavenJava': POM file is invalid. Check any modifications you have made to the POM file.
```

2023-03-18 16:57 UTC, galovics requested changes

2023-03-18 16:57 UTC, galovics commented on build.gradle
> +                'fineract-provider'
The addition causes a failure for the publication for me and for the openMF/fineract repo.

2023-03-21 01:10 UTC, IOhacker commented
Closing this PR

2023-03-21 01:10 UTC, closed without merging