FINERACT-1905: New repayment strategy
apache/fineract pull request #3065
Opened 2023-03-21 15:13 UTC by adamsaghy

## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2023-03-21 20:21 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/loanaccount/domain/LoanChargeEffectiveDueDateComparator.java
> +public class LoanChargeEffectiveDueDateComparator implements Comparator<LoanCharge> {
Make this a singleton class if there's a specific instance to use (i.e. drop the public constructor)

2023-03-22 10:00 UTC, adamsaghy commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/loanaccount/domain/LoanChargeEffectiveDueDateComparator.java
> +public class LoanChargeEffectiveDueDateComparator implements Comparator<LoanCharge> {
👍

2023-03-22 12:53 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/loanaccount/starter/LoanAccountAutoStarter.java
> +    @ConditionalOnProperty("fineract.loan.transactionprocessor.due-date-respective.enabled")
Would be better to have the property mapped to the FineractProperties class and then using a PropertiesCondition for this. That way it's going to be type-safe and the property name is not duplicated.

2023-03-24 15:29 UTC, galovics requested changes

2023-03-24 15:29 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/core/config/FineractProperties.java
> +        private FineractTransactionProcessorProperties transactionprocessor;
Java naming convention pls. Should be `transactionProcessor`, note the capital `P`

2023-03-27 09:10 UTC, ruchiD reviewed
LGTM

2023-03-27 12:12 UTC, galovics approved these changes

2023-03-27 12:12 UTC, merged