FINERACT-1724-Regular-loan-cob-job-having-catch-up-true
apache/fineract pull request #3108
Opened 2023-04-07 15:39 UTC by ruchiD

## Description
Modified saving is_catch_up job parameter to custom job parameters as json.
Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2023-04-11 07:06 UTC, galovics requested changes

2023-04-11 07:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/core/service/database/DatabaseSpecificSQLGenerator.java
> +    public String jsonAppender() {
I think based on the castChar method, this should be castJson.

2023-04-11 07:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/core/service/database/DatabaseSpecificSQLGenerator.java
> +            throw new IllegalStateException("Database type is not supported for current schema " + databaseTypeResolver.databaseType());
Copy paste typo on the error msg.

2023-04-11 07:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/jobs/domain/CustomJobParameterRepository.java
> +public interface CustomJobParameterRepository extends JpaRepository<CustomJobParameter, Long>, JobCustomParameterRepository {}
I think we should get rid of the JpaRepository interface here completely cause it's not working properly (the save method for example, since that's why you have the custom repository implementation).

2023-04-11 07:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/jobs/domain/JobCustomParameterRepository.java
> +    Long saveCustomJobParameter(String jsonString);
Should be called save simply (after removing the JpaRepository)

2023-04-11 07:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/jobs/domain/JobCustomParameterRepositoryImpl.java
> +                + databaseSpecificSQLGenerator.jsonAppender() + ")");
This would look much better with the approach I mentioned in the generator class (like castChar).

2023-04-11 07:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/jobs/domain/JobCustomParameterRepositoryImpl.java
> +        insertSqlStatementBuilder.append("INSERT INTO batch_custom_job_parameters (parameter_json) VALUES (:jsonString"
Let's try to use formatting, makes it much easier to read.
```
"INSERT INTO ... VALUES (%s)".formatted(generator.castJson(":jsonString"))
```

2023-04-11 07:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/jobs/domain/JobCustomParameterRepositoryImpl.java
> +                .queryForObject("SELECT " + databaseSpecificSQLGenerator.lastInsertId(), Long.class);
Formatting here pls. Bonus point if you put this into a constant so this is cached. (note: not necessarily a constant into this class but somewhere else where anybody can reuse it)

2023-04-11 07:06 UTC, galovics commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/jobs/domain/JobExecutionRepository.java
> +            throw new IllegalStateException("Database type is not supported for current schema " + databaseTypeResolver.databaseType());
Error msg.

2023-04-11 07:06 UTC, galovics commented on fineract-provider/src/main/resources/db/changelog/tenant/parts/0103_modify_parameter_json_column_custom_job_parameters.xml
> +        <modifyDataType columnName="parameter_json"
Does this modification work if you already had string values in the table?

2023-04-11 17:15 UTC, ruchiD commented on fineract-provider/src/main/resources/db/changelog/tenant/parts/0103_modify_parameter_json_column_custom_job_parameters.xml
> +        <modifyDataType columnName="parameter_json"
Yes

2023-04-12 05:56 UTC, ruchiD commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/jobs/domain/JobCustomParameterRepositoryImpl.java
> +                .queryForObject("SELECT " + databaseSpecificSQLGenerator.lastInsertId(), Long.class);
Hi Arnold, I was not sure about this change..and i think its not fixed the way you expected in refactored code. Please elaborate a bit.

2023-04-12 09:07 UTC, adamsaghy approved these changes
LGTM

2023-04-12 12:14 UTC, ruchiD commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/core/service/database/DatabaseSpecificSQLGenerator.java
> +    public String jsonAppender() {
Fixed

2023-04-12 12:14 UTC, ruchiD commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/core/service/database/DatabaseSpecificSQLGenerator.java
> +            throw new IllegalStateException("Database type is not supported for current schema " + databaseTypeResolver.databaseType());
Fixed

2023-04-12 12:15 UTC, ruchiD commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/jobs/domain/CustomJobParameterRepository.java
> +public interface CustomJobParameterRepository extends JpaRepository<CustomJobParameter, Long>, JobCustomParameterRepository {}
Fixed

2023-04-12 12:15 UTC, ruchiD commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/jobs/domain/JobCustomParameterRepository.java
> +    Long saveCustomJobParameter(String jsonString);
Fixed

2023-04-12 12:15 UTC, ruchiD commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/jobs/domain/JobCustomParameterRepositoryImpl.java
> +                + databaseSpecificSQLGenerator.jsonAppender() + ")");
Fixed

2023-04-12 12:15 UTC, ruchiD commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/jobs/domain/JobCustomParameterRepositoryImpl.java
> +        insertSqlStatementBuilder.append("INSERT INTO batch_custom_job_parameters (parameter_json) VALUES (:jsonString"
Fixed

2023-04-12 12:15 UTC, ruchiD commented on fineract-provider/src/main/java/org/apache/fineract/infrastructure/jobs/domain/JobExecutionRepository.java
> +            throw new IllegalStateException("Database type is not supported for current schema " + databaseTypeResolver.databaseType());
Fixed

2023-04-12 12:53 UTC, merged