FINERACT-1926: Fineract Asset Externalization - GET Pagination
apache/fineract pull request #3202
Opened 2023-05-25 09:41 UTC by b0c1

- [x] Added Pagination to response
- [x] Added limit and offset to the request

## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2023-05-26 08:10 UTC, galovics requested changes

2023-05-26 08:10 UTC, galovics commented on fineract-core/src/main/java/org/apache/fineract/infrastructure/core/service/Page.java
> +    public static <E> Page<E> convertFromSpringPage(final org.springframework.data.domain.Page<E> springPage) {
Let's remove this.

2023-05-26 08:10 UTC, galovics commented on fineract-investor/src/main/java/org/apache/fineract/investor/service/ExternalAssetOwnersReadServiceImpl.java
> +        org.springframework.data.domain.Page<ExternalAssetOwnerTransfer> result;
No need for qualified name.

2023-05-26 08:10 UTC, galovics commented on fineract-investor/src/main/java/org/apache/fineract/investor/service/ExternalAssetOwnersReadServiceImpl.java
> +            result = externalAssetOwnerTransferRepository.findAllByLoanId(loanId, pageRequest);
I think for all these repository calls where we use pageable we are missing a crucial thing, a consistent ordering of the result. Let's do an ID based ordering at least for the query to produce consistent results between runs.

2023-05-26 08:10 UTC, galovics commented on integration-tests/src/test/java/org/apache/fineract/integrationtests/investor/externalassetowner/InitiateExternalAssetOwnerTransferTest.java
> +            Page<Map<String, Object>> retrieveResponseMap = new Gson().fromJson(retrieveResponse, retrieveType);
I think we need an additional test case to verify that paging is working. Don't you think?

2023-05-30 08:01 UTC, adamsaghy commented
@b0c1 Kindly asking you to check the failing tests!

2023-05-31 06:42 UTC, galovics approved these changes

2023-05-31 15:15 UTC, merged