FINERACT-1926: Asset transfer to external owner COB business step
apache/fineract pull request #3207
Opened 2023-05-26 14:42 UTC by adamsaghy

## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2023-05-30 10:45 UTC, ruchiD reviewed
LGTM from functional/use cases perspective.
Is adding this business step to cob job a separate change. (liquibase script to add step to cob, integrating/configuring this step with fineract-provider)

2023-05-30 11:05 UTC, taskain7 reviewed
please check my comments

2023-05-30 11:05 UTC, taskain7 commented on fineract-investor/src/main/java/org/apache/fineract/investor/cob/loan/LoanAccountOwnerTransferBusinessStep.java
> +            ExternalTransferStatus secondTransferStatus = transferDataList.get(0).getStatus();
this is also the first element of the list

2023-05-30 11:05 UTC, taskain7 commented on fineract-investor/src/main/java/org/apache/fineract/investor/cob/loan/LoanAccountOwnerTransferBusinessStep.java
> +        return loan.getLoanSummary().getTotalOutstanding().compareTo(BigDecimal.ZERO) > 0;
I think we should also check if the loan is in active status.
Or is the positive totalOutstanding implicitly means that the loan is active?

2023-05-30 11:05 UTC, taskain7 commented on fineract-investor/src/main/java/org/apache/fineract/investor/cob/loan/LoanAccountOwnerTransferBusinessStep.java
> +        LocalDate openEnded = LocalDate.of(9999, 12, 31);
We use this multiple times, it would be a good idea to extract it to a global constant

2023-05-30 11:05 UTC, taskain7 commented on fineract-investor/src/main/java/org/apache/fineract/investor/cob/loan/LoanAccountOwnerTransferBusinessStep.java
> +    public Loan execute(Loan loan) {
could you write some unit tests for this, to cover the use-cases?

2023-05-30 11:16 UTC, adamsaghy commented on fineract-investor/src/main/java/org/apache/fineract/investor/cob/loan/LoanAccountOwnerTransferBusinessStep.java
> +        return loan.getLoanSummary().getTotalOutstanding().compareTo(BigDecimal.ZERO) > 0;
it means that, yeah...

2023-05-30 11:38 UTC, galovics requested changes

2023-05-30 11:38 UTC, galovics commented on fineract-investor/src/main/java/org/apache/fineract/investor/cob/loan/LoanAccountOwnerTransferBusinessStep.java
> +            throw new IllegalStateException(
I understand the purpose of this, but don't you think it'd be better to catch this when submitting a transfer?

2023-05-30 11:38 UTC, galovics commented on fineract-investor/src/main/java/org/apache/fineract/investor/service/ExternalAssetOwnersReadServiceImpl.java
> +    @Override
Let's not let entities past through the transactional boundary (i.e. the service is annotated with Transactional so anything that's coming out of that will be detached) and could cause maintenance issues in the future (just like for the majority of fineract today).

2023-05-30 11:38 UTC, galovics commented on fineract-investor/src/main/java/org/apache/fineract/investor/service/ExternalAssetOwnersWriteService.java
> +    ExternalAssetOwnerTransfer save(ExternalAssetOwnerTransfer externalAssetOwnerTransfer);
Same as above for the read service on boundaries.

2023-05-30 11:38 UTC, galovics commented on fineract-investor/src/main/java/org/apache/fineract/investor/service/ExternalAssetOwnersWriteService.java
> +    ExternalAssetOwnerTransferLoanMapping createActiveMapping(Long loanId, ExternalAssetOwnerTransfer externalAssetOwnerTransfer);
Same as above for the read service on boundaries.

2023-05-30 11:38 UTC, galovics commented on fineract-investor/src/main/java/org/apache/fineract/investor/service/ExternalAssetOwnersWriteService.java
> +    void removeActiveMapping(Long loanId, ExternalAssetOwnerTransfer externalAssetOwnerTransfer);
Bonus: here as well since the parameter is an entity.

2023-05-30 11:38 UTC, galovics commented on fineract-investor/src/main/java/org/apache/fineract/investor/service/ExternalAssetOwnersWriteServiceImpl.java
> +    @Transactional
Let's simply annotate the class instead.

2023-05-30 15:59 UTC, adamsaghy commented
> LGTM from functional/use cases perspective.
> Is adding this business step to cob job a separate change. (liquibase script to add step to cob, integrating/configuring this step with fineract-provider)

It will not be added by default.

2023-05-31 06:38 UTC, galovics approved these changes

2023-05-31 06:42 UTC, merged