MIFOSX-2149-Surplus Payment Treatment for Loan
apache/fineract pull request #351
Opened 2017-05-10 13:57 UTC by Ippezrobert

2017-06-09 05:19 UTC, nazeer1100126 requested changes

2017-06-09 05:19 UTC, nazeer1100126 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/loanaccount/service/LoanWritePlatformServiceJpaRepositoryImpl.java
> +                    final AccountAssociations accountAssociations = this.accountAssociationRepository.findByLoanIdAndType(loanId,AccountAssociationType.LINKED_ACCOUNT_ASSOCIATION.getValue());
What happens when linked savings account is not available? There might be a null pointer exception here.

2017-06-09 05:19 UTC, nazeer1100126 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/loanproduct/data/LoanProductData.java
> +	private final boolean canAutoAllocateOverpayments;
I believe, when canAutoAllocateOverpayments is enabled from loan product definition, then we need to mandate linked savings account for the loans created from this product

2017-06-13 15:19 UTC, Ippezrobert commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/loanaccount/service/LoanWritePlatformServiceJpaRepositoryImpl.java
> +                    final AccountAssociations accountAssociations = this.accountAssociationRepository.findByLoanIdAndType(loanId,AccountAssociationType.LINKED_ACCOUNT_ASSOCIATION.getValue());
I thought 
if(loanIds != null){ 
Will handle this exception

2017-06-16 15:15 UTC, nazeer1100126 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/loanaccount/service/LoanWritePlatformServiceJpaRepositoryImpl.java
> +                    final AccountAssociations accountAssociations = this.accountAssociationRepository.findByLoanIdAndType(loanId,AccountAssociationType.LINKED_ACCOUNT_ASSOCIATION.getValue());
Assume a case with over paid loans which doesn't have linked savings account. That time accountAssociations will be null right?

2017-06-20 11:57 UTC, closed without merging