FINERACT-1971: Enhanced error logging: Optimistic lock exception handling + log most specific exception
apache/fineract pull request #3761
Opened 2024-02-20 13:25 UTC by adamsaghy

## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2024-02-21 15:10 UTC, galovics requested changes

2024-02-21 15:10 UTC, galovics commented on fineract-core/src/main/java/org/apache/fineract/infrastructure/core/exceptionmapper/JakartaOptimisticLockExceptionMapper.java
> +@Scope("singleton")
Annotation not needed.

2024-02-21 15:10 UTC, galovics commented on fineract-core/src/main/java/org/apache/fineract/infrastructure/core/exceptionmapper/JakartaOptimisticLockExceptionMapper.java
> +        return 4019;
I assume this should be 409.

2024-02-21 15:10 UTC, galovics commented on fineract-core/src/main/java/org/apache/fineract/infrastructure/core/exceptionmapper/JpaOptimisticLockExceptionMapper.java
> +@Scope("singleton")
Same as for the other.

2024-02-21 15:10 UTC, galovics commented on fineract-core/src/main/java/org/apache/fineract/infrastructure/core/exceptionmapper/JpaOptimisticLockExceptionMapper.java
> +        return 4019;
Same as for the other.

2024-02-21 15:17 UTC, adamsaghy commented on fineract-core/src/main/java/org/apache/fineract/infrastructure/core/exceptionmapper/JakartaOptimisticLockExceptionMapper.java
> +        return 4019;
It is a more specific error code, but does not reflect the http code

2024-02-21 15:17 UTC, adamsaghy commented on fineract-core/src/main/java/org/apache/fineract/infrastructure/core/exceptionmapper/JpaOptimisticLockExceptionMapper.java
> +        return 4019;
It is a more specific error code, but does not reflect the http code

2024-02-22 14:42 UTC, galovics approved these changes

2024-02-22 15:09 UTC, merged