Client search v2 using Client Identifiers
apache/fineract pull request #3829
Opened 2024-03-26 07:08 UTC by alberto-art3ch

## Description

Client search v2 using Client Identifiers in the search values as we have in the general search endpoint. There is not impact or change needed in the UI

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

<img width="1901" alt="Screenshot 2024-03-26 at 12 50 40 a m" src="https://github.com/apache/fineract/assets/154766431/74f9c5a5-98f8-4691-b053-1e069616efed">

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2024-03-26 09:10 UTC, adamsaghy commented on fineract-core/src/main/java/org/apache/fineract/portfolio/client/domain/Client.java
> +    protected Set<ClientIdentifier> identifiers = new HashSet<>();
Why do we need this new association? It is not used anywhere

2024-03-26 09:10 UTC, adamsaghy requested changes
Kindly add the proper FINERACT story for this PR and check my review!

2024-04-04 05:16 UTC, alberto-art3ch commented
> Kindly add the proper FINERACT story for this PR and check my review!

Done

2024-04-04 08:20 UTC, adamsaghy commented
Please update the Commit message too!

2024-04-09 18:04 UTC, adamsaghy commented
Please update the Commit message too!

2024-04-09 22:22 UTC, alberto-art3ch commented
> Please update the Commit message too!

Done! Commit message updated

2024-04-11 13:36 UTC, adamsaghy approved these changes
LGTM

2024-05-17 11:20 UTC, adamsaghy requested changes
Please check the failing build!

2024-05-21 09:32 UTC, adamsaghy approved these changes
LGTM

2024-05-21 09:32 UTC, merged