FINERACT-2107: Interest Refund - Partial Refund cases
apache/fineract pull request #4116
Opened 2024-10-22 05:51 UTC by somasorosdpc

## Description

[FINERACT-2107](https://issues.apache.org/jira/browse/FINERACT-2107): Interest Refund - Partial Refund cases

Interest Refund calculation on Payout Refund and Merchant Issued Refund if configured for interest bearing progressive loans. + Integration tests
** covering partial refund in single transaction.

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2024-10-29 22:04 UTC, adamsaghy commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/loanaccount/service/ProgressiveLoanInterestRefundServiceImpl.java
> +                        new LoanTransaction(lt.getLoan(), lt.getLoan().getOffice(), REPAYMENT.getValue(), lt.getDateOf(), lt.getAmount(),
Can you please tell me about this? I thought we were just amending the disbursement and calculate interest based on the remaining amount.

2024-10-30 08:27 UTC, galovics requested changes

2024-10-30 08:27 UTC, galovics commented on integration-tests/src/test/java/org/apache/fineract/integrationtests/LoanInterestRefundTest.java
> +                    // transaction(5.75, "Accrual", "22 January 2021"), //
Comment.

2024-10-30 08:27 UTC, galovics commented on integration-tests/src/test/java/org/apache/fineract/integrationtests/LoanInterestRefundTest.java
> +                    // transaction(2.46, "Accrual", "22 January 2021"), //
Comment.

2024-10-30 08:27 UTC, galovics commented on integration-tests/src/test/java/org/apache/fineract/integrationtests/LoanInterestRefundTest.java
> +    // @Test
Comment.

2024-10-30 08:27 UTC, galovics commented on integration-tests/src/test/java/org/apache/fineract/integrationtests/LoanInterestRefundTest.java
> +    private void logLoanDetails(GetLoansLoanIdResponse loanDetails) {
This doesn't only log, please name the method appropriately.

2024-10-30 08:27 UTC, galovics commented on integration-tests/src/test/java/org/apache/fineract/integrationtests/LoanInterestRefundTest.java
> +                            .addSupportedInterestRefundTypesItem("MERCHANT_ISSUED_REFUND") //
Would it be possible to create constants for these static values? Would be much better for maintainability.

2024-10-30 09:17 UTC, somasorosdpc commented on integration-tests/src/test/java/org/apache/fineract/integrationtests/LoanInterestRefundTest.java
> +    // @Test
I removed the unused test case too

2024-10-30 09:18 UTC, somasorosdpc commented on integration-tests/src/test/java/org/apache/fineract/integrationtests/LoanInterestRefundTest.java
> +                            .addSupportedInterestRefundTypesItem("MERCHANT_ISSUED_REFUND") //
I've created a static class in Base class for options, and removed the unnecessary `.supportedInterestRefundTypes(new ArrayList<>())`

2024-10-30 12:16 UTC, merged