FINERACT-2156: Confirm existance of elements before accessing them
apache/fineract pull request #4202
Opened 2024-12-01 21:40 UTC by wkigenyi

## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2024-12-30 10:14 UTC, adamsaghy commented on hs_err_pid7500.log
> +#
Please remove this.

2024-12-30 10:14 UTC, adamsaghy commented on hs_err_pid8972.log
> +#
Please remove this.

2024-12-30 10:14 UTC, adamsaghy requested changes
Please kindly remove the log files!

2024-12-30 19:20 UTC, wkigenyi commented on hs_err_pid8972.log
> +#
Removed

2025-01-01 01:14 UTC, wkigenyi commented
@adamsaghy this is now ready for review

2025-01-01 14:50 UTC, adamsaghy commented on fineract-savings/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccount.java
> -            SavingsAccountTransaction savingsAccountTransactionFirst = savingsAccountTransaction.get(0);
Would you mind to simplify the logic a little bit further?

You can merge the `savingsAccountTransaction != null` and `savingsAccountTransaction.size() > 0` condition together and if they are TRUE take the running balance of the first element otherwise it is BigDecimal.ZERO (if there are no any transaction the running balance must be 0). 
After you can deduct the `amountPaid` from the above balance and if the balance is negative and `allowOverdraft` is FALSE then `InsufficientAccountBalanceException` to be thrown.

I believe it would be easier to read and cover better the requirements!

Also kindly asking you to write a test (it can be unit tests), which covers the following situations:
- `savingsAccountTransaction` is empty and `amountPaid` is positive and `allowOverdraft = true` -> **No exception!**
- `savingsAccountTransaction` is empty and `amountPaid` is positive and `allowOverdraft = false` -> **Exception to be thrown!**
- `savingsAccountTransaction` is not empty and `amountPaid` is positive and `amountPaid` is higher than the running balance of the 1st transaciton and `allowOverdraft = true` -> **No exception!**
- `savingsAccountTransaction` is not empty and `amountPaid` is positive and `amountPaid` is lower than the running balance of the 1st transaction and `allowOverdraft = false` -> **Exception to be thrown!**
- `savingsAccountTransaction` is not empty and `amountPaid` is positive and `amountPaid` is equal with the running balance of the 1st transaction and `allowOverdraft = false` -> **No exception!**

2025-01-01 14:50 UTC, adamsaghy requested changes
@wkigenyi Kindly see my review!

2025-02-04 19:28 UTC, galovics commented
@wkigenyi any plans to continue this PR?

2025-02-04 19:31 UTC, wkigenyi commented
Yes I work on it. Been busy with some back log.

2025-03-03 03:31 UTC, IOhacker commented on fineract-savings/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccount.java
> -            SavingsAccountTransaction savingsAccountTransactionFirst = savingsAccountTransaction.get(0);
@wkigenyi Are you still working on the ticket?

2025-03-03 07:50 UTC, wkigenyi commented
Hello Victor,

I will make effort to close it within the week.

Regards.
Wilfred

On Mon, Mar 3, 2025 at 6:32 AM Víctor Romero ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> fineract-savings/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccount.java
> <https://github.com/apache/fineract/pull/4202#discussion_r1976830959>:
>
> > @@ -1594,12 +1594,19 @@ public void validateAccountBalanceDoesNotBecomeNegative(final String transaction
>      public void validateAccountBalanceDoesNotViolateOverdraft(final List<SavingsAccountTransaction> savingsAccountTransaction,
>              final BigDecimal amountPaid) {
>          if (savingsAccountTransaction != null) {
> -            SavingsAccountTransaction savingsAccountTransactionFirst = savingsAccountTransaction.get(0);
>
> @wkigenyi <https://github.com/wkigenyi> Are you still working on the
> ticket?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/apache/fineract/pull/4202#discussion_r1976830959>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEK6IQ7NAS5GE6GD2VGNAX32SPELLAVCNFSM6AAAAABS2DOJRSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDMNJSHE4DONBZHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-03-06 20:37 UTC, wkigenyi commented on fineract-savings/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccount.java
> -            SavingsAccountTransaction savingsAccountTransactionFirst = savingsAccountTransaction.get(0);
@adamsaghy should the case in bullet 4 throw an exception ? `amountPaid` is _LOWER_ than the `runningBalance`. In this case I think the exception should not be thrown

2025-03-10 21:19 UTC, wkigenyi commented
@adamsaghy could you guide me on how to fix this test? The result says it got status 403 instead of the 400 that was expected. In the test I specified:
```
assertEquals("error.msg.savingsaccount.transaction.insufficient.account.balance",
                savingsAccountErrorData.get(0).get(CommonConstants.RESPONSE_ERROR_MESSAGE_CODE));
```
I am not sure that status code is being considered instead of the string I specified.

2025-03-11 17:57 UTC, adamsaghy commented on fineract-savings/src/main/java/org/apache/fineract/portfolio/savings/domain/SavingsAccount.java
> -            SavingsAccountTransaction savingsAccountTransactionFirst = savingsAccountTransaction.get(0);
Yes, the bullet 3 and 4 might be should do the opposite!

2025-03-14 12:59 UTC, merged