FINERACT-2148: Stop recalculating interest if the loan is charged-off
apache/fineract pull request #4234
Opened 2024-12-22 23:00 UTC by alberto-art3ch

## Description

When we are reprocessing the transactions of the loan, anything that happened before the Charge-off transaction can and should recalculate interest, but after the Charge-off transaction, neither of the transactions should trigger interest recalculation anymore!

[FINERACT-2148](https://issues.apache.org/jira/browse/FINERACT-2148)

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

2024-12-27 12:33 UTC, kulminsky approved these changes

2024-12-27 12:49 UTC, mariiaKraievska commented on fineract-loan/src/main/java/org/apache/fineract/portfolio/loanaccount/service/LoanScheduleService.java
> +        if (loan.repaymentScheduleDetail().isInterestRecalculationEnabled() && !loan.isChargedOff()) {
When you call loan.isChargedOff(), it simply checks whether the loan has been charged off. As a result, you might skip the recalculation for installments that have dates earlier than the charge-off transaction. As far as I understand, you need to stop recalculating interest only AFTER the date of the charge-off transaction. Perhaps my PR could help you: https://github.com/apache/fineract/pull/4236

2024-12-30 12:23 UTC, adamsaghy requested changes
Kindly check Maria's review!

2025-01-07 16:06 UTC, adamsaghy commented on fineract-loan/src/main/java/org/apache/fineract/portfolio/loanaccount/domain/Loan.java
> +        if (!this.repaymentScheduleDetail().isEnableDownPayment() && (!this.repaymentScheduleDetail().isInterestRecalculationEnabled()
This is not correct out of box. isChargedOff() was sufficient here...

2025-01-07 16:06 UTC, adamsaghy commented on fineract-loan/src/main/java/org/apache/fineract/portfolio/loanaccount/domain/Loan.java
> +        if (!this.repaymentScheduleDetail().isEnableDownPayment() && (!this.repaymentScheduleDetail().isInterestRecalculationEnabled()
recalculate from is null many situations, but still we dont wanna recalculate schedule...

2025-01-07 16:09 UTC, adamsaghy commented on fineract-loan/src/main/java/org/apache/fineract/portfolio/loanaccount/service/LoanScheduleService.java
> +        if (loanSchedule == null || loan.isChargedOff()) {
Not needed... it is redundant... loan.getRecalculatedSchedule(generatorDTO) will return null if loan is charged off

2025-01-07 16:09 UTC, adamsaghy requested changes
Kindly see my review!

2025-01-08 05:40 UTC, alberto-art3ch commented on fineract-loan/src/main/java/org/apache/fineract/portfolio/loanaccount/service/LoanScheduleService.java
> +        if (loan.repaymentScheduleDetail().isInterestRecalculationEnabled() && !loan.isChargedOff()) {
Solved!

2025-01-08 05:44 UTC, alberto-art3ch commented on fineract-loan/src/main/java/org/apache/fineract/portfolio/loanaccount/service/LoanScheduleService.java
> +        if (loanSchedule == null || loan.isChargedOff()) {
Updated!

2025-01-08 05:44 UTC, alberto-art3ch commented on fineract-loan/src/main/java/org/apache/fineract/portfolio/loanaccount/domain/Loan.java
> +        if (!this.repaymentScheduleDetail().isEnableDownPayment() && (!this.repaymentScheduleDetail().isInterestRecalculationEnabled()
Updated!

2025-01-08 11:07 UTC, merged