glim_gsim
apache/fineract pull request #492
Opened 2018-11-17 16:59 UTC by rrpawar96

addressed comments mentioned in https://github.com/apache/fineract/pull/445

2018-11-21 17:12 UTC, rahulg963 requested changes

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/accountdetails/data/AccountSummaryCollectionData.java
> +<<<<<<< HEAD
Hi, can you please solve these merge conflicts and remove these from the file.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/accountdetails/data/AccountSummaryCollectionData.java
> +>>>>>>> 5ecaff5dc... gsim and glim functionalities added
same as above.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/accountdetails/data/AccountSummaryCollectionData.java
> +<<<<<<< HEAD
same as above.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/accountdetails/data/AccountSummaryCollectionData.java
> +=======
same as above.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/accountdetails/data/AccountSummaryCollectionData.java
> +>>>>>>> 5ecaff5dc... gsim and glim functionalities added
same as above.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/accountdetails/data/SavingsAccountSummaryData.java
> +
Please remove extra empty lines from here.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/accountdetails/data/SavingsSummaryCustom.java
> +	private final Long id;
Please maintain file formatting structure.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/accountdetails/service/AccountDetailsReadPlatformServiceJpaRepositoryImpl.java
> +=======
Please solve merge conflicts and remove these.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/accountdetails/service/AccountDetailsReadPlatformServiceJpaRepositoryImpl.java
> +>>>>>>> 5ecaff5dc... gsim and glim functionalities added
Please solve merge conflicts and remove these.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/accountdetails/service/AccountDetailsReadPlatformServiceJpaRepositoryImpl.java
> +<<<<<<< HEAD
Please solve merge conflicts and remove these.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/accountdetails/service/AccountDetailsReadPlatformServiceJpaRepositoryImpl.java
> +=======
Please solve merge conflicts and remove these.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/accountdetails/service/AccountDetailsReadPlatformServiceJpaRepositoryImpl.java
> +>>>>>>> 5ecaff5dc... gsim and glim functionalities added
Please solve merge conflicts and remove these.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/accountdetails/service/AccountDetailsReadPlatformServiceJpaRepositoryImpl.java
> +<<<<<<< HEAD
Please solve merge conflicts and remove these.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/accountdetails/service/AccountDetailsReadPlatformServiceJpaRepositoryImpl.java
> +=======
Please solve merge conflicts and remove these.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/accountdetails/service/AccountDetailsReadPlatformServiceJpaRepositoryImpl.java
> +>>>>>>> 5ecaff5dc... gsim and glim functionalities added
Please solve merge conflicts and remove these.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/group/api/GroupsApiResource.java
> +
Please ensure proper file formatting here.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/group/exception/GroupMemberNotFoundInGSIMException.java
> +public class GroupMemberNotFoundInGSIMException extends AbstractPlatformDomainRuleException
Please ensure proper file formatting here.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/loanaccount/domain/GroupLoanIndividualMonitoringAccount.java
> +
Pleas remove extra empty lines from here.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/loanaccount/service/LoanReadPlatformService.java
> +<<<<<<< HEAD
Please solve merge conflicts and remove these.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/loanaccount/service/LoanReadPlatformService.java
> +=======
Please solve merge conflicts and remove these.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/loanaccount/service/LoanReadPlatformService.java
> +>>>>>>> 5ecaff5dc... gsim and glim functionalities added
Please solve merge conflicts and remove these.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/loanaccount/service/LoanWritePlatformServiceJpaRepositoryImpl.java
> +    @Override
Please ensure proper file formatting here.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/api/SavingsAccountsApiResource.java
> +            //
If you need to add some comments here then kindly do so.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountWritePlatformServiceJpaRepositoryImpl.java
> +<<<<<<< HEAD
Please solve merge conflicts and remove these.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountWritePlatformServiceJpaRepositoryImpl.java
> +=======
Please solve merge conflicts and remove these.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountWritePlatformServiceJpaRepositoryImpl.java
> +>>>>>>> 5ecaff5dc... gsim and glim functionalities added
Please solve merge conflicts and remove these.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountWritePlatformServiceJpaRepositoryImpl.java
> +<<<<<<< HEAD
Please solve merge conflicts and remove these.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountWritePlatformServiceJpaRepositoryImpl.java
> +>>>>>>> 5ecaff5dc... gsim and glim functionalities added
Please solve merge conflicts and remove these.

2018-11-21 17:12 UTC, rahulg963 commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/savings/service/SavingsAccountWritePlatformServiceJpaRepositoryImpl.java
> +    public CommandProcessingResult gsimActivate(final Long gsimId, final JsonCommand command) {
Please ensure proper file formatting here.

2018-12-11 16:13 UTC, edcable commented
Hi @rahulg963 and @rrpawar96 How is this task looking for shipment in 1.3?

2018-12-26 06:43 UTC, ShruthiRajaram commented
@rrpawar96 your contribution is valuable. Kindly address the comments , so that this can be included in Fineract 1.3 release.

2018-12-31 09:59 UTC, rahulg963 commented
@rrpawar96 Please solve the merge conflicts.

@edcable @ShruthiRajaram

2018-12-31 10:03 UTC, ShruthiRajaram commented
@rahulg963 , @rrpawar96 has raised PR here #504 . Please check

2019-02-04 15:35 UTC, vorburger commented
@rrpawar96 thank you very much for your interest in and contribution to Fineract/Mifos!  I'm an (old) volunteer who got reminded of Mifos/Fineract this week-end at the FOSDEM conference, and I'm taking a moment to help the project clean up some of it's old issues and pull requests etc.  

We were wondering whether you are still alive, and would be willing to `git rebase develop` this PR and take any previous review feedback into account?  If we don't hear from you within 2 weeks, we will take the liberty to close this PR without merging it, to avoid confusion for future new contributors looking at this repository - hope you understand and that's fair.

2019-02-05 14:32 UTC, rrpawar96 commented
Yes, @vorburger Since New PR has been raised. [#504](https://github.com/apache/fineract/pull/504). You can close this PR.

2019-02-05 14:33 UTC, vorburger commented
> Yes, @vorburger Since New PR has been raised. [#504](https://github.com/apache/fineract/pull/504). You can close this PR.

@rrpawar96 may I let you close it yourself?

2019-02-05 14:39 UTC, closed without merging