[MIFOSX-2114] Change assignment staff to groups and clients in center.
apache/fineract pull request #514
Opened 2019-02-08 10:01 UTC by TypicalGitHubUser

Recreated from #275.

2019-02-15 23:14 UTC, vorburger commented
@TypicalGitHubUser would you mind to re-rebase this, so that Travis CI will run on it?

@nazeer1100126 will you re-review this as requested in #275 ?

2019-03-02 22:26 UTC, vishwasbabu requested changes

2019-03-02 22:26 UTC, vishwasbabu commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/client/service/ClientWritePlatformServiceJpaRepositoryImpl.java
> +                final Long staffId = command.longValueOfParameterNamed(ClientApiConstants.staffIdParamName);
If the Client has a parent group, but the parent group does not have a center, the else condition would not execute and staffId passed in through the API call would be lost. You would now end up with a Client with no staff assigned when the API caller had explicitly passed in a staffId

Ideally, the behavior should be such that.

1) If the staffId is passed in through the API call, set the same to the client
2) If not, inherit the staffId from the client's parent (if the client has a parent)

2019-03-02 22:26 UTC, vishwasbabu commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/group/service/GroupingTypesWritePlatformServiceJpaRepositoryImpl.java
> +                    staff = parentGroup.getStaff();
Same issue as the previous comment

2019-03-02 22:26 UTC, vishwasbabu commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/group/service/GroupingTypesWritePlatformServiceJpaRepositoryImpl.java
> +                        newStaff = groupForUpdate.getParent().getStaff();
Here too

2019-03-02 22:26 UTC, vishwasbabu commented on fineract-provider/src/main/java/org/apache/fineract/portfolio/client/service/ClientWritePlatformServiceJpaRepositoryImpl.java
> +                final Long staffId = command.longValueOfParameterNamed(ClientApiConstants.staffIdParamName);
Please add an integration test case which validates the functional changes made

2019-03-08 06:53 UTC, vishwasbabu commented
@TypicalGitHubUser : Please let us know if you have the time to address these review comments anytime in the near future. If not, we shall be closing this PR on the 15th of March in an effort to help committers have a clearer view of pending pull requests. Hope you understand and think this is fair.

2019-03-10 15:04 UTC, TypicalGitHubUser commented
@vishwasbabu No, I won't be able to do this in near future.

2019-03-10 15:05 UTC, TypicalGitHubUser commented
@vishwasbabu No, I won't be able to do this in near future.

2019-03-11 07:53 UTC, vishwasbabu commented
Closing this PR

2019-03-11 07:53 UTC, closed without merging